version: "3.3"
services:
  stock-prev-v3-the-prophet:
    build:
      context: .
      dockerfile: Dockerfile.tf2
    restart: on-failure # `always` makes start on boot
    environment:
      CLEANUP_BEFORE: "False"
      COMPRESS_AFTER: "True"
      NAS_PARALLELISM: "1"
      LSTM_PARALLELISM: "0"
      STOCK_LIST: "goog,pg,jnj,mmm,ko"
      START_DATE: "01/01/2002"
      END_DATE: "31/12/2022"
      MODE: "NAS"
      SS_ID: "LessNodeTypes"
      POP_SZ: "70"
      MAX_EVAL: "1050"
      NAS_ALG: "NSGAIII"
      NAS_OBJ: "5"
      NAS_REF_DIRS_CONF: "(-1, 1)"
      AGG_METHOD: "VOTING_MEDIAN"
      FAULT_HANDLER: "True"
      TF_EXP_OPT_OFF: "True"
      # TF_LOG_OFF: "True"
    volumes:
      - ./datasets:/code/datasets
      - ./hyperparameters:/code/hyperparameters
      - ./logs:/code/logs
      - ./models:/code/models
      - ./nas:/code/nas
      - ./prophets:/code/prophets
      - ./saved_plots:/code/saved_plots
      - ./experiments:/code/experiments
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
        limits:
          memory: 60G
