version: "3.3"
services:
  stock-prev-v3-the-prophet:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      CLEANUP_BEFORE: "False"
      COMPRESS_AFTER: "True"
      NAS_PARALLELISM: "-4"
      LSTM_PARALLELISM: "-4"
      STOCK_LIST: "goog,pg,jnj,mmm,ko"
      START_DATE: "01/01/2002"
      END_DATE: "30/11/2022"
      MODE: "NAS"
      SS_ID: "LessNodeTypes"
      POP_SZ: "70"
      MAX_EVAL: "1540"
      NAS_ALG: "NSGAIII"
      NAS_OBJ: "5"
      NAS_REF_DIRS_CONF: "(-1, 1)"
      AGG_METHOD: "VOTING_MEDIAN"
    volumes:
      - ./datasets:/code/datasets
      - ./hyperparameters:/code/hyperparameters
      - ./logs:/code/logs
      - ./models:/code/models
      - ./nas:/code/nas
      - ./prophets:/code/prophets
      - ./saved_plots:/code/saved_plots
      - ./experiments:/code/experiments
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "30"
          memory: 150G
