version: '3.3'

services:
  stock-prev-v3-the-prophet:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      COMPRESS_AFTER: "True"
      NAS_PARALLELISM: "0"
      LSTM_PARALLELISM: "1"
      STOCK_LIST: "goog,pg,jnj,mmm,ko"
      START_DATE: "01/01/2002"
      END_DATE: "30/11/2022"
      MODE: "NAS"
      SS_ID: "SearchSpace"
      POP_SZ: "2000"
      CHILDREN_SZ: "2000"
      MAX_EVAL: "6000"
      NAS_ALG: "NSGAIII"
      NAS_OBJ: "5"
      AGG_METHOD: "VOTING_EXP_F_WEIGHTED_AVERAGE"
    volumes:
      - ./datasets:/code/datasets
      - ./hyperparameters:/code/hyperparameters
      - ./logs:/code/logs
      - ./models:/code/models
      - ./nas:/code/nas
      - ./prophets:/code/prophets
      - ./saved_plots:/code/saved_plots
      - ./experiments:/code/experiments
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '10'
          memory: 70G
        reservation:
          cpus: '4'
          memory: 10G
